std = "lua51"
max_line_length = false

globals = {
    "C_AddOns",
    "C_SpecializationInfo",
    "C_Timer",
    "CreateFrame",
    "DEFAULT_CHAT_FRAME",
    "GetGuildInfo",
    "GetInventoryItemLink",
    "GetInventorySlotInfo",
    "GetProfessionInfo",
    "GetProfessions",
    "GetRealmName",
    "GetServerTime",
    "GuildweaverDB",
    "SLASH_GUILDWEAVER1",
    "SLASH_GUILDWEAVER2",
    "SlashCmdList",
    "UIParent",
    "UISpecialFrames",
    "UnitClass",
    "UnitFullName",
    "UnitGUID",
    "UnitLevel",
    "UnitName",
    "UnitRace",
    "UnitSex",
}
